NAME := mindset_instructions

main: 
		gcc source/main.c -o $(NAME)

index: 
		gcc source/indexer_without_float-tail.c -o indexer_without_float-tail

indexWft:
		gcc source/indexer_with_float-tail.c.c -o indexer_with_float-tail

list:
		gcc source/list.c -o list