NAME := mindset_instructions

main: 
		gcc source/main.c -o $(NAME)

index: 
		gcc source/indexer_without_float-tail.c -o indexer_without_float-tail

indexWft:
		gcc source/indexer_with_float-tail.c.c -o indexer_with_float-tail

mdset:
		gcc source/md_set[2]-md_set[16].c -o md_set

list:
		gcc source/list.c -o list